using System;

namespace Engine
{
    public enum InputKey
    {
        InputKeyUnrecognized = 0,

        InputKeyKeyboardArrowUp,
        InputKeyKeyboardArrowDown,
        InputKeyKeyboardArrowLeft,
        InputKeyKeyboardArrowRight,

        InputKeyKeyboardCtrlLeft,
        InputKeyKeyboardCtrlRight,
        InputKeyKeyboardAltLeft,
        InputKeyKeyboardAltRight,
        InputKeyKeyboardShiftLeft,
        InputKeyKeyboardShiftRight,
        InputKeyKeyboardSystemLeft,
        InputKeyKeyboardSystemRight,

        InputKeyKeyboardCommand,
        InputKeyKeyboardOption,
        InputKeyKeyboardEsc,
        InputKeyKeyboardTab,
        InputKeyKeyboardSpace,
        InputKeyKeyboardBackspace,
        InputKeyKeyboardEnter,
        InputKeyKeyboardInsert,
        InputKeyKeyboardDelete,
        InputKeyKeyboardHome,
        InputKeyKeyboardEnd,
        InputKeyKeyboardPageUp,
        InputKeyKeyboardPageDown,
        InputKeyKeyboardPauseBreak,
        InputKeyKeyboardPrintScreen,
        InputKeyKeyboardCapsLock,
        InputKeyKeyboardScrollLock,
        InputKeyKeyboardNumLock,

        InputKeyKeyboardNumpad1,
        InputKeyKeyboardNumpad2,
        InputKeyKeyboardNumpad3,
        InputKeyKeyboardNumpad4,
        InputKeyKeyboardNumpad5,
        InputKeyKeyboardNumpad6,
        InputKeyKeyboardNumpad7,
        InputKeyKeyboardNumpad8,
        InputKeyKeyboardNumpad9,
        InputKeyKeyboardNumpad0,
        InputKeyKeyboardNumpadEnter,
        InputKeyKeyboardNumpadDecimal,
        InputKeyKeyboardNumpadAdd,
        InputKeyKeyboardNumpadSubtract,
        InputKeyKeyboardNumpadMultiply,
        InputKeyKeyboardNumpadDivide,

        InputKeyKeyboardTilde,
        InputKeyKeyboardHyphen,
        InputKeyKeyboardEquals,
        InputKeyKeyboardBracketLeft,
        InputKeyKeyboardBracketRight,
        InputKeyKeyboardBackslash,
        InputKeyKeyboardSemicolon,
        InputKeyKeyboardQuote,
        InputKeyKeyboardComma,
        InputKeyKeyboardPeriod,
        InputKeyKeyboardSlash,

        InputKeyKeyboardF1,
        InputKeyKeyboardF2,
        InputKeyKeyboardF3,
        InputKeyKeyboardF4,
        InputKeyKeyboardF5,
        InputKeyKeyboardF6,
        InputKeyKeyboardF7,
        InputKeyKeyboardF8,
        InputKeyKeyboardF9,
        InputKeyKeyboardF10,
        InputKeyKeyboardF11,
        InputKeyKeyboardF12,

        InputKeyKeyboard1,
        InputKeyKeyboard2,
        InputKeyKeyboard3,
        InputKeyKeyboard4,
        InputKeyKeyboard5,
        InputKeyKeyboard6,
        InputKeyKeyboard7,
        InputKeyKeyboard8,
        InputKeyKeyboard9,
        InputKeyKeyboard0,

        InputKeyKeyboardA,
        InputKeyKeyboardB,
        InputKeyKeyboardC,
        InputKeyKeyboardD,
        InputKeyKeyboardE,
        InputKeyKeyboardF,
        InputKeyKeyboardG,
        InputKeyKeyboardH,
        InputKeyKeyboardI,
        InputKeyKeyboardJ,
        InputKeyKeyboardK,
        InputKeyKeyboardL,
        InputKeyKeyboardM,
        InputKeyKeyboardN,
        InputKeyKeyboardO,
        InputKeyKeyboardP,
        InputKeyKeyboardQ,
        InputKeyKeyboardR,
        InputKeyKeyboardS,
        InputKeyKeyboardT,
        InputKeyKeyboardU,
        InputKeyKeyboardV,
        InputKeyKeyboardW,
        InputKeyKeyboardX,
        InputKeyKeyboardY,
        InputKeyKeyboardZ,

        InputKeyMouseCursor,
        InputKeyMouseLeft,
        InputKeyMouseMiddle,
        InputKeyMouseRight,
        InputKeyMouse4,
        InputKeyMouse5,
        InputKeyMouseWheelUp,
        InputKeyMouseWheelDown,

        InputKeyJoystick,

        InputKeyGamepadStickLeft,
        InputKeyGamepadStickRight,
        InputKeyGamepadA,
        InputKeyGamepadB,
        InputKeyGamepadX,
        InputKeyGamepadY,
        InputKeyGamepadDpadUp,
        InputKeyGamepadDpadDown,
        InputKeyGamepadDpadLeft,
        InputKeyGamepadDpadRight,
        InputKeyGamepadTriggerLeft1,
        InputKeyGamepadTriggerLeft2,
        InputKeyGamepadTriggerRight1,
        InputKeyGamepadTriggerRight2,

        InputKeyUpperBound
    }

    public interface IKeyNode : INode
    {
        bool BindInputToLocaleAction(Action<InputKey, string> pLocaleAction);
        void UnbindInputFromLocaleAction();

        bool BindInputKeyToAction(InputKey pKey, Action<InputKey> pAction);
        void UnbindInputKeyFromAction(InputKey pKey);
    }
}